# Generated by Django 3.1 on 2020-08-11 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statemodel',
            fields=[
                ('Stateid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('States', models.CharField(max_length=100, verbose_name='State Name')),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'State List',
                'verbose_name_plural': 'State List',
                'db_table': 'StateTbl',
            },
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('Tourid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('TournamentName', models.CharField(max_length=250, verbose_name='Tournament Name')),
                ('RegStartDate', models.DateField(verbose_name='Registration Start Date')),
                ('RegEndDate', models.DateField(verbose_name='Registration End Date')),
                ('TournamentStartDate', models.DateField(verbose_name='Tournament Start Date')),
                ('TournamentEndDate', models.DateField(verbose_name='Tournament End Date')),
                ('AllowedTeams', models.IntegerField(verbose_name='Team Registration Restriction')),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('Venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.statemodel')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'Tournament List',
                'verbose_name_plural': 'Tournament List',
                'db_table': 'TournamentTbl',
            },
        ),
        migrations.CreateModel(
            name='RegisteredTournamentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('TeamName', models.CharField(max_length=255, unique=True, verbose_name='Team Name')),
                ('CoachName', models.CharField(max_length=255, verbose_name='Coach Name')),
                ('ManagerName', models.CharField(max_length=255, verbose_name='Manager Name')),
                ('RegiserStatus', models.BooleanField(default=False, verbose_name='Register Status')),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('TournamentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournamentmodel')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'Registered List',
                'verbose_name_plural': 'Registered List',
                'db_table': 'RegisteredTournamentTbl',
            },
        ),
    ]
