# Generated by Django 3.1 on 2020-08-12 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('GameDate', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('Team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='Tournaments.registeredtournamentmodel', verbose_name='Team1 Name')),
                ('Team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='Tournaments.registeredtournamentmodel', verbose_name='Team2 Name')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'Match Schedule List',
                'verbose_name_plural': 'Match Schedule List',
                'db_table': 'MatchScheduleTbl',
            },
        ),
    ]
