# Generated by Django 3.1 on 2020-08-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0002_matchschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchschedule',
            name='TournametId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournamentmodel', verbose_name='TournamentID'),
        ),
    ]
