# Generated by Django 3.1 on 2020-08-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0003_matchschedule_tournametid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredtournamentmodel',
            name='RegiserStatus',
            field=models.BooleanField(default=True, verbose_name='Register Status'),
        ),
    ]
